// Mocks generated by Mockito 5.4.5 from annotations
// in meal_app/test/use_cases/search_categories_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:meal_app/app/data/meal_api.dart' as _i2;
import 'package:meal_app/features/categories/domain/repositories/category_repository.dart'
    as _i6;
import 'package:meal_app/features/categories/entities/dto/category_dto.dart'
    as _i3;
import 'package:meal_app/features/categories/entities/models/category_model.dart'
    as _i7;
import 'package:meal_app/features/meal_details/entities/dtos/meal_details_dto.dart'
    as _i5;
import 'package:meal_app/features/meals/entities/dto/meal_item_dto.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMealApi_0 extends _i1.SmartFake implements _i2.MealApi {
  _FakeMealApi_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoryDto_1 extends _i1.SmartFake implements _i3.CategoryDto {
  _FakeCategoryDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMealDto_2 extends _i1.SmartFake implements _i4.MealDto {
  _FakeMealDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMealDetailsDto_3 extends _i1.SmartFake
    implements _i5.MealDetailsDto {
  _FakeMealDetailsDto_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i6.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MealApi get mealApi =>
      (super.noSuchMethod(
            Invocation.getter(#mealApi),
            returnValue: _FakeMealApi_0(this, Invocation.getter(#mealApi)),
          )
          as _i2.MealApi);

  @override
  set categories(List<_i7.CategoryModel>? _categories) => super.noSuchMethod(
    Invocation.setter(#categories, _categories),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<List<_i7.CategoryModel>> getCategories({bool? refresh = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, [], {#refresh: refresh}),
            returnValue: _i8.Future<List<_i7.CategoryModel>>.value(
              <_i7.CategoryModel>[],
            ),
          )
          as _i8.Future<List<_i7.CategoryModel>>);
}

/// A class which mocks [MealApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockMealApi extends _i1.Mock implements _i2.MealApi {
  MockMealApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i3.CategoryDto> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i8.Future<_i3.CategoryDto>.value(
              _FakeCategoryDto_1(this, Invocation.method(#getCategories, [])),
            ),
          )
          as _i8.Future<_i3.CategoryDto>);

  @override
  _i8.Future<_i4.MealDto> getMeals(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#getMeals, [category]),
            returnValue: _i8.Future<_i4.MealDto>.value(
              _FakeMealDto_2(this, Invocation.method(#getMeals, [category])),
            ),
          )
          as _i8.Future<_i4.MealDto>);

  @override
  _i8.Future<_i5.MealDetailsDto> getMealDetailsById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMealDetailsById, [id]),
            returnValue: _i8.Future<_i5.MealDetailsDto>.value(
              _FakeMealDetailsDto_3(
                this,
                Invocation.method(#getMealDetailsById, [id]),
              ),
            ),
          )
          as _i8.Future<_i5.MealDetailsDto>);
}

/// A class which mocks [CategoryModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryModel extends _i1.Mock implements _i7.CategoryModel {
  @override
  String get category =>
      (super.noSuchMethod(
            Invocation.getter(#category),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#category),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#category),
            ),
          )
          as String);

  @override
  String get thumbnail =>
      (super.noSuchMethod(
            Invocation.getter(#thumbnail),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#thumbnail),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#thumbnail),
            ),
          )
          as String);

  @override
  String get description =>
      (super.noSuchMethod(
            Invocation.getter(#description),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#description),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.getter(#description),
            ),
          )
          as String);

  @override
  String searchProp() =>
      (super.noSuchMethod(
            Invocation.method(#searchProp, []),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#searchProp, []),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.method(#searchProp, []),
            ),
          )
          as String);
}
