// Mocks generated by Mockito 5.4.5 from annotations
// in meal_app/test/cubit/category_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:meal_app/features/categories/domain/repositories/category_repository.dart'
    as _i2;
import 'package:meal_app/features/categories/domain/use_cases/fetch_categories_use_case.dart'
    as _i5;
import 'package:meal_app/features/categories/domain/use_cases/search_categories_use_case.dart'
    as _i7;
import 'package:meal_app/features/categories/entities/models/category_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCategoryRepository_0 extends _i1.SmartFake
    implements _i2.CategoryRepository {
  _FakeCategoryRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CategoryModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryModel extends _i1.Mock implements _i3.CategoryModel {
  @override
  String get category =>
      (super.noSuchMethod(
            Invocation.getter(#category),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#category),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.getter(#category),
            ),
          )
          as String);

  @override
  String get thumbnail =>
      (super.noSuchMethod(
            Invocation.getter(#thumbnail),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#thumbnail),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.getter(#thumbnail),
            ),
          )
          as String);

  @override
  String get description =>
      (super.noSuchMethod(
            Invocation.getter(#description),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#description),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.getter(#description),
            ),
          )
          as String);

  @override
  String searchProp() =>
      (super.noSuchMethod(
            Invocation.method(#searchProp, []),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#searchProp, []),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.method(#searchProp, []),
            ),
          )
          as String);
}

/// A class which mocks [FetchCategoriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchCategoriesUseCase extends _i1.Mock
    implements _i5.FetchCategoriesUseCase {
  MockFetchCategoriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryRepository get categoryRepository =>
      (super.noSuchMethod(
            Invocation.getter(#categoryRepository),
            returnValue: _FakeCategoryRepository_0(
              this,
              Invocation.getter(#categoryRepository),
            ),
          )
          as _i2.CategoryRepository);

  @override
  _i6.Future<List<_i3.CategoryModel>> execute([bool? refresh = false]) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [refresh]),
            returnValue: _i6.Future<List<_i3.CategoryModel>>.value(
              <_i3.CategoryModel>[],
            ),
          )
          as _i6.Future<List<_i3.CategoryModel>>);
}

/// A class which mocks [SearchCategoriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchCategoriesUseCase extends _i1.Mock
    implements _i7.SearchCategoriesUseCase {
  MockSearchCategoriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryRepository get categoryRepository =>
      (super.noSuchMethod(
            Invocation.getter(#categoryRepository),
            returnValue: _FakeCategoryRepository_0(
              this,
              Invocation.getter(#categoryRepository),
            ),
          )
          as _i2.CategoryRepository);

  @override
  _i6.Future<List<_i3.CategoryModel>> execute([String? keyword = '']) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [keyword]),
            returnValue: _i6.Future<List<_i3.CategoryModel>>.value(
              <_i3.CategoryModel>[],
            ),
          )
          as _i6.Future<List<_i3.CategoryModel>>);

  @override
  List<_i3.CategoryModel> search(
    List<_i3.CategoryModel>? source,
    String? keyword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#search, [source, keyword]),
            returnValue: <_i3.CategoryModel>[],
          )
          as List<_i3.CategoryModel>);
}
